clarify vagrant provider, packer builder

diff --git a/exec/basebox-add b/exec/basebox-add
--- a/exec/basebox-add
+++ b/exec/basebox-add
@@ -3,25 +3,28 @@
 function main {
   local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
 
-  local nm_only="$1"; shift
+  local nm_provider="$1"; shift
   local pth_box=
 
-  case "$nm_only" in
-    virtualbox|vmware|parallels|digitalocean|aws)
+  case "$nm_provider" in
+    virtualbox|vmware|parallels|aws)
       true ;;
+    digitalocean|digital_ocean)
+      nm_provider="digitalocean"
+      ;;
     *)
-      if [[ -f "$nm_only" ]]; then
-        pth_box="$nm_only"
-        nm_only=
+      if [[ -f "$nm_provider" ]]; then
+        pth_box="$nm_provider"
+        nm_provider=
       else
-        echo ERROR: "Invalid virtualization type: $nm_only" 1>&2
+        echo ERROR: "Invalid virtualization type: $nm_provider" 1>&2
         return 1
       fi
       ;;
   esac
 
   cd "$shome"
-  vagrant box add --name ubuntu${1:+"-$1"} "${pth_box:-"$(set +f; ls -d "$shome/box/$nm_only"/*${1:+-$1*}.box | sort | head -1)"}"
+  vagrant box add --name ubuntu${1:+"-$1"} "${pth_box:-"$(set +f; ls -d "$shome/box/$nm_provider"/*${1:+-$1*}.box | sort | head -1)"}"
 }
 
 source sub "$0" "$@"
diff --git a/exec/basebox-remove b/exec/basebox-remove
--- a/exec/basebox-remove
+++ b/exec/basebox-remove
@@ -3,25 +3,25 @@
 function main {
   local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
 
-  local nm_only="$1"; shift
+  local nm_vagrant_provider="$1"; shift
   local pth_box=
 
-  case "$nm_only" in
+  case "$nm_vagrant_provider" in
     vmware)
-      nm_only="vmware_desktop"
+      nm_vagrant_provider="vmware_desktop"
       ;;
-    digitalocean)
-      nm_only="digital_ocean"
+    digitalocean|digital_ocean)
+      nm_vagrant_provider="digital_ocean"
       ;;
     virtualbox|parallels|aws)
       true ;;
     *)
-      echo ERROR: "Invalid virtualization type: $nm_only" 1>&2
+      echo ERROR: "Invalid virtualization type: $nm_vagrant_provider" 1>&2
       return 1
       ;;
   esac
 
-  vagrant box remove --provider "$nm_only" ubuntu${1:+"-$1"}
+  vagrant box remove --provider "$nm_vagrant_provider" ubuntu${1:+"-$1"}
 }
 
 source sub "$0" "$@"
